language: python
python:
  - "3.9"

before_install:
  - pip install pycodestyle

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - python -m pytest tests/
  - coverage run --source="src/" -m pytest
  - pycodestyle src/ --ignore=E722,E501,E402